### ISSUE TITLE
How to build a Shader without the [glsl|...|] syntax ?

### ISSUE THREAD

**Issue by titouanc** [elm-explorations/webgl#40]
The documentation states

> [Normally you specify a shader with a `[glsl| |]` block.](https://github.com/elm-explorations/webgl/blob/main/src/WebGL.elm#L179-L180)

Is there any other way to build a Shader without the `[glsl| ...|]` syntactical construct ? I would like to generate shader code in Elm, and therefore I don't have any shader code at compile time to put in there.

**Comment by w0rm** [comment]
@titouanc this used to work in the past through the unsafe shader function. The functionality was removed in 0.19 because the shader inputs depend on Elm record field names. Starting from 0.19 the field names are mangled when compiled in the optimize mode (to reduce asset size). In order for these names to match, the shader inputs had to be known at compile time.

**Comment by titouanc** [comment]
Thanks for your fast reply @w0rm !
Unless you have another suggestion that would allow me to use native Elm webgl, I will then resort to ports and manage the webgl context in javascript.
